server:
  port: $[server.port]
  http:
    port: $[server.port]
  tomcat:
    max-threads: 10
  baseAddress: https://weixin.miaochen.wang
  ssl:
    key-store: classpath:tomcat.p12
    key-store-password: woshi#0930
    key-store-type: PKCS12
    key-alias: tomcat

spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 30MB
  application:
    name: $[server.name]
  devtools:
    restart:
      enabled: true
    additional-paths: resources/**,static/**,templates/**
  thymeleaf:
    cache: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 填写你数据库的url、登录名、密码和数据库名
    url: $[datasource.url]
    username: $[datasource.username]
    password: $[datasource.password]
    druid:
      # 连接池的配置信息
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /tool/datasource/*
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  redis:
    host: localhost
    port: 6379
    password:

mybatis-plus:
  mapper-locations: $[mybatis.mapper-locations]
  typeAliasesPackage: $[mybatis.type-aliases-package]

app:
  swagger:
    enable: true
  jwt:
    key: TianGongWeb2018*+-.@#!^
    content: TianGong Server Token
    timeout: 86400000
    token:
      rediskey: user_%s_token_%s

## 微信公众号配置
wx:
  mp:
    # 自动回复消息发送间隔（毫秒），适当增加间隔可提升用户体验
    autoReplyInterval: 1000
    configs:
      - appid: wx5deed3a14709dd32
        secret: fc9e5f54deebfc27af47f115c8f42584
        token: RY65b3C6Z3BU3Z85EergN5777c73328B
        aesKey: zrxEpzt2X0tCkQXKqMZqMqmqqXLxREMXqYYYctmdKPl
  pay:
    appId:  #微信公众号或者小程序等的appid
    mchId:  #微信支付商户号
    mchKey:  #微信支付商户密钥
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: classpath:/cert/wx-pay-cert.p12 # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
    useSandBoxEnv: true #是否使用微信支付沙箱测试环境
